# -*- coding: utf-8 -*-
"""carga_streamlit_script_influencers.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1SFVvoPtnL8ydWj3XYOp9kZTFwxDaZEoC
"""

# pip install streamlit

import pandas as pd
import numpy as np
# import tweepy
import ast
import csv
import time
import json
import os
#from google.colab import drive, files
import plotly.express as px  # pip install plotly-express
import streamlit as st

st.set_page_config(page_title="People Analytics Twitter Influencers", page_icon=":bar_chart:", layout="wide")

# ---- MAINPAGE ----
st.title(":bar_chart: People Analytics Twitter Influencers")
st.markdown("##")

#drive.mount('/content/drive')
#uploaded = files.upload()

ruta_archivo = 'User activity.xlsx'

# ruta_archivo = 'https://github.com/ManueLorenzoBouz/TwitterDash/blob/2920d8828a9bcb8e221e856acba27c5b7fb66ff8/User%20activity.xlsx'

user_activity = pd.read_excel('User activity.xlsx')

data = user_activity.describe().round(0)

top_influencers = px.bar(user_activity[user_activity['Followers']>user_activity['Followers'].mean()].sort_values(by='Followers'), x='Followers', y='User name', orientation='h')

#one_column = st.columns(1)
#one_column.plotly_chart(top_influencers, use_container_width=True)

passive_audience = px.bar(user_activity[user_activity['Retweets received']>user_activity['Retweets received'].mean()].sort_values(by='Retweets received'), x='Retweets received', y='User name', orientation='h')

relevance_matrix = px.scatter(
    user_activity, y='Retweets received', x='Followers', hover_data=['User name'])

network = px.scatter(
    user_activity, y='Active network', x='Passive network', hover_data=['User name'])

left_column, right_column = st.columns(2)
left_column.plotly_chart(network, use_container_width=True)
right_column.plotly_chart(relevance_matrix, use_container_width=True)

# ---- HIDE STREAMLIT STYLE ----
hide_st_style = """
            <style>
            #MainMenu {visibility: hidden;}
            footer {visibility: hidden;}
            header {visibility: hidden;}
            </style>
            """
st.markdown(hide_st_style, unsafe_allow_html=True)
